services:
  - type: web
    name: terrain3d
    env: static
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
