/* ════════════════════════════════════════════
   STL EXPORT — Binary STL download
   Collects all meshes from the terrain group and writes a binary STL file.
   ════════════════════════════════════════════ */

import * as THREE from 'three';
import { state } from '../state';

/**
 * Binary STL format:
 *   80 bytes  : header
 *    4 bytes  : uint32 triangle count
 *   Per tri   : 12 (normal) + 36 (3 vertices) + 2 (attrib) = 50 bytes
 */
export function exportSTL(filename = 'terrain3d.stl') {
  if (!state.tg) return;

  // Collecter tous les triangles
  const triangles: Array<[THREE.Vector3, THREE.Vector3, THREE.Vector3]> = [];
  const _pos = new THREE.Vector3(), _norm = new THREE.Vector3();

  state.tg.traverse(obj => {
    if (!(obj instanceof THREE.Mesh)) return;
    const geo = obj.geometry as THREE.BufferGeometry;
    const posAttr = geo.attributes.position as THREE.BufferAttribute;
    if (!posAttr) return;
    const idxAttr = geo.index;

    // World matrix
    const mat4 = obj.matrixWorld;

    function getVert(i: number): THREE.Vector3 {
      const v = new THREE.Vector3(posAttr.getX(i), posAttr.getY(i), posAttr.getZ(i));
      v.applyMatrix4(mat4);
      // Scale mm → mm (déjà en mm, pas besoin de conversion)
      return v;
    }

    if (idxAttr) {
      for (let i = 0; i < idxAttr.count; i += 3) {
        triangles.push([
          getVert(idxAttr.getX(i)),
          getVert(idxAttr.getX(i + 1)),
          getVert(idxAttr.getX(i + 2)),
        ]);
      }
    } else {
      for (let i = 0; i < posAttr.count; i += 3) {
        triangles.push([getVert(i), getVert(i + 1), getVert(i + 2)]);
      }
    }
  });

  if (!triangles.length) {
    alert('Aucune géométrie à exporter. Générez d\'abord le terrain 3D.');
    return;
  }

  // Écriture binaire STL
  const buf = new ArrayBuffer(80 + 4 + triangles.length * 50);
  const view = new DataView(buf);

  // Header
  const enc = new TextEncoder();
  const header = enc.encode('Terrain3D STL - generated by terrain3d.app');
  for (let i = 0; i < Math.min(header.length, 80); i++) view.setUint8(i, header[i]);

  // Triangle count
  view.setUint32(80, triangles.length, true);

  let offset = 84;
  const _e1 = new THREE.Vector3(), _e2 = new THREE.Vector3();
  for (const [a, b, c] of triangles) {
    // Compute face normal
    _e1.subVectors(b, a);
    _e2.subVectors(c, a);
    _norm.crossVectors(_e1, _e2).normalize();

    // Normal
    view.setFloat32(offset, _norm.x, true); offset += 4;
    view.setFloat32(offset, _norm.y, true); offset += 4;
    view.setFloat32(offset, _norm.z, true); offset += 4;
    // Vertices
    for (const v of [a, b, c]) {
      view.setFloat32(offset, v.x, true); offset += 4;
      view.setFloat32(offset, v.y, true); offset += 4;
      view.setFloat32(offset, v.z, true); offset += 4;
    }
    // Attribute
    view.setUint16(offset, 0, true); offset += 2;
  }

  // Téléchargement
  const blob = new Blob([buf], { type: 'application/octet-stream' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);

  console.log(`STL exporté: ${triangles.length} triangles, ${(buf.byteLength / 1024).toFixed(0)} KB`);
}
